# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer require --dev phpunit/phpunit ^7
  displayName: 'Instalar phpunit'

- script: composer require --dev phpunit/dbunit
  displayName: 'Instalar dbunit'

- script: composer require --dev phpmd/phpmd
  displayName: 'Instalar Mess detector'

- script: cat composer.json
  displayName: 'Verificar Configuración Composer'

- script: sudo chmod 777 /home/vsts/work/1/s/vendor/phpunit/phpunit/phpunit
  displayName: 'Permiso para phpunit'

- script: sudo chmod 777 /home/vsts/work/1/s/vendor/phpmd/phpmd/src/bin/phpmd
  displayName: 'Permiso para Mess Detector'

- script: chmod +x vendor/bin/phpunit
  displayName: 'Identificar phpunit como ejecutable'

- script: chmod +x vendor/bin/phpmd
  displayName: 'Identificar phpmd como ejecutable'

- script: ./vendor/bin/phpmd capa_negocios ansi cleancode
  displayName: 'Pruebas de Codigo'

- script: ./vendor/bin/phpmd capa_negocios ansi codesize
  displayName: 'Pruebas de Codigo'

- script: ./vendor/bin/phpmd capa_negocios ansi unusedcode
  displayName: 'Pruebas de Codigo'

- script: ./vendor/bin/phpmd capa_negocios ansi naming
  displayName: 'Pruebas de Codigo'

- script: ./vendor/bin/phpunit testUnitarios --color
  displayName: 'Pruebas unitarias de las Clases'

- tarea: PublishBuildArtifacts @ 1
